### ISSUE TITLE
Tag colour not displayed after selecting tag when creating new snippet

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#11]
When you select a tag to assign to your Snippet, it does not use the tag's colour, but instead uses the macOS accent colour:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/586075/215612040-465e476b-3be2-4308-b0b4-0fc041a87f9a.png">

The CodeMirror tag should be green on the snippet.

**Comment by JTostitos** [comment]
Add/Edit View has been redesigned and now shows the accent color of the specific tag that is chosen
