### ISSUE TITLE
Can no longer add tags or languages

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#12]
The add tags and languages field has disappeared in the latest build (21):

<img width="411" alt="image" src="https://user-images.githubusercontent.com/586075/215937052-f59a4c44-5f45-4a27-b0af-d853abdb2f70.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/586075/215937167-777db4c0-cf34-4912-b460-460834f37ce3.png">

**Comment by JTostitos** [comment]
Next Build - Fixed
