### ISSUE TITLE
Edit snippet shows on right pane

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#13]
Since you said that adding a new snippet should be in its own window, which is is in build 21, I think editing should also be in the window. Instead, it's crammed into the details pane. Makes it more consistent.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/586075/215937399-951c8f93-9b85-4086-824b-14da771d93b3.png">

Also rather than right-click to edit, how about double-clicking? Or add an explicit Edit button on the detail pane when you select a snippet.

**Comment by JTostitos** [comment]
Editing is now in its own window
