### ISSUE TITLE
Snippets Pro Upgrade screen scrolling issue and observations.

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#5]
The features list on top scrolls, but the pricing list down below doesn't and was initially truncated at the bottom. I had to manually resize the window to show all the pricing options.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/586075/215606952-09d5b709-dd09-4513-9a79-036ec021131c.png">

It's weird that the (x) button on the Snippets Pro upgrade screen closes the whole Settings window.  Maybe the Snippets Pro Upgrade option should be its own tab?  The slide over to the new screen feels wrong for a Mac app there.

**Comment by trozware** [comment]
Thanks for this report. The only way I found to get back from the upgrade screen was to quit the app, but expanding the window showed me the exit buttons. I did not see the subscription buttons.

**Comment by JTostitos** [comment]
@trozware @brendand Yes, I am aware of this issue. For now, you can expand the height of the window, and there should be a back button in the top left of the view right above the big Snippets Pro title. The (x) button will eventually be removed. I am also still deciding how to display that view anyways. It was a temporary measure. Thanks.

**Comment by JTostitos** [comment]
It is now shown in a sheet when you open this view from the settings window. The X button remains in order to close the sheet.
