### ISSUE TITLE
About should be on the About panel, not in the Settings window

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#6]
Also the other screens in Settings have a grey background, but About has a white background. Should be consistent.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/586075/215607913-e7bdd95f-73c4-4a56-8d92-aadb5aa6c6a2.png">

**Comment by JTostitos** [comment]
Turned into a form on Mac and stays as a list on iOS
