### ISSUE TITLE
Adding new tag and pressing return dismisses window and you lose your tag

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#7]
By default I assumed I could type in a tag name and press Return to add it to the list of tags. But when I did that, the window disappeared and the tag I entered was gone. The `[+]` button appeared to be the default command when pressing Return, but instead the Done button was. Perhaps making the Done button not activate on Return would be ideal in this case. You could then quickly create tags by typing the tag name and pressing return. 

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/586075/215608467-f3a662b8-adac-432e-b1e5-75e9f3d76aac.png">

**Comment by JTostitos** [comment]
Next Build - Fixed
- press return to add tag
- press escape to close sheet
