### ISSUE TITLE
Cannot change the colour of a tag

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#8]
I created 3 tags and wanted to go back to edit the colours. The message said `Right click to edit or delete`. On a Mac, control-click is the same as right-click. That did not work. So I two-finger clicked to display the contextual menu. I selected `Color` and the colour picker displayed. I chose a different colour. The colour swatch at the bottom left changed to the selected colour, but it did not get applied to the selected tag.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/586075/215609979-10b52408-4cf7-489c-adce-79a370442b37.png">

Also, you can't seem to select a tag on the tags edit window.

After I dismissed the colour picker, I could no longer bring it back up. Selecting `Color` from the contextual menu did nothing.

**Comment by JTostitos** [comment]
**Next Build**
control click now works as expected
using a third party dependency for a color picker on macOS now so there shouldn't be any issue with it not appearing on subsequent attempts to use it.

@brendand Can you explain in further detail what you mean by "you can't seem to select a tag on the tags edit window"? 
> It is intentional not to be able to select a tag on the tags view when clicking the tags button in the toolbar. But you can however, click to select one when the sheet appears from the edit snippet view.

**Comment by brendand** [comment]
When I see a list of items, I generally expect to be able to select them. With your Tags and Languages list, clicking on the tags doesn't do anything when you just want to edit them. You must right-click to display the contextual menu, then select an option. 

<img width="412" alt="image" src="https://user-images.githubusercontent.com/586075/216226756-068a21b8-1722-476a-8e70-dcb4214888f6.png">

But you could just allow selection of the tag or language and display the details down below such that you can edit the values and the colour. Without the contextual menu.

Please don't take this as criticism, but just my feelings. It feels like you're taking an iOS app and trying to squeeze it into a Mac. Is this a Catalyst app? The conventions you're using feel very iOS like and not very Mac like. That's just my opinion as a Mac and iOS app developer myself.

**Comment by JTostitos** [comment]
@brendand No, it isn't a catalyst app, its SwiftUI and AppKit. I originally tried Catalyst but there were just too many issues with no way given to a dev to fix. I wanted to make Snippets Studio a Mac app long before the iOS version. However, SwiftUI was terrible on anything earlier than Ventura so the iOS version came first.

I understand what you said now. I'll see if there is something I can do to make a selection interaction meaningful in these two views.

In the next update there is a fix to allow creating new snippets and editing the colors on existing ones. Thanks for the feedback.

**Comment by JTostitos** [comment]
- [x] Fix Control Click
- [x] Fix Disappearing Color Picker
- [x] Right Click to edit tag color
~~Tag/Lang selection?~~

**Comment by brendand** [comment]
Ah interesting. I just thought it might be Catalyst because I've seen a few of those that have dialogues that fade up like that and feel like they're UIViews being presented instead of AppKit. I'm also using some SwiftUI in my Mac app.

I guess there's more Mac and iOS differences you have to account for even in SwiftUI apps. Keep up the great work!
