### ISSUE TITLE
Resizing the window causes the sidebar to collapse

### ISSUE THREAD

**Issue by brendand** [JTostitos/snippets-enhancements-bugs#9]
I wanted to resize the window so the right content would display (it's truncated initially). As soon as I widened the window, the sidebar collapsed:

Before Resizing:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/586075/215610574-2cedb16b-08cd-4b2b-8420-ead5f2f10f58.png">

After resizing:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/586075/215610622-646db5ad-8e29-4588-9c19-16f68700ee32.png">

**Comment by abhimat** [comment]
Also seeing this consistently! Sidebar opens again upon clicking the sidebar button.

**Comment by JTostitos** [comment]
Next Build - Fixed
Set a default minimum window size to prevent sidebar collapse
